# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.8'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  ## 后端服务，注意修改 智能体 DRAWIOAGENT 配置。
  ai-draw-io-app:
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-draw-io-app:1.6
#    image: fuzhengwei/ai-draw-io-app:1.0
    container_name: ai-draw-io-app
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      # 智能体 DRAWIOAGENT 配置，更换 base_url、api_key、model、以及百度搜索的 api_key 「https://console.bce.baidu.com/iam/?_=1753597622044#/iam/apikey/list」
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_AI_API_BASE_URL=https://apis.itedus.cn
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_AI_API_API_KEY=sk-S2YffPknMOEbapquA84c9004294248568d1a3fDdAfA137C9
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_AI_API_COMPLETIONS_PATH=v1/chat/completions
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_CHAT_MODEL_MODEL=gpt-4.1
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_NAME=baidu-search
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_BASE_URI=http://appbuilder.baidu.com/v2/ai_search/mcp/
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_SSE_ENDPOINT=sse?api_key=bce-v3/ALTAK-WjK8NIh3txZo7rXXEjhri/e2f09d53de961bcaf2609b76c7c7a7e6d0f05da3
      - AI_AGENT_CONFIG_TABLES_DRAWIOAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_REQUEST_TIMEOUT=500000
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_AI_API_BASE_URL=https://apis.itedus.cn
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_AI_API_API_KEY=sk-S2YffPknMOEbapquA84c9004294248568d1a3fDdAfA137C9
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_CHAT_MODEL_MODEL=gpt-4.1
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_AI_API_COMPLETIONS_PATH=v1/chat/completions
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_NAME=baidu-search
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_BASE_URI=http://appbuilder.baidu.com/v2/ai_search/mcp/
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_SSE_ENDPOINT=sse?api_key=bce-v3/ALTAK-WjK8NIh3txZo7rXXEjhri/e2f09d53de961bcaf2609b76c7c7a7e6d0f05da3
      - AI_AGENT_CONFIG_TABLES_PPTAGENT_MODULE_CHAT_MODEL_TOOL_MCP_LIST_0_SSE_REQUEST_TIMEOUT=500000
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

  ## 前端服务，注意 image 如果你有自己的镜像，记得更换。
  ai-draw-io-front:
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/ai-draw-io-front:1.5
#    image: fuzhengwei/ai-draw-io-front:1.0
    container_name: ai-draw-io-front
    restart: always
    ports:
      - "3000:3000"
    environment:
      # 修改 http://192.168.1.110:8091/api/v1 为你的IP地址。
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://81.70.245.73:8091/api/v1}
      - NODE_ENV=production

networks:
  my-network:
    driver: bridge
